---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: metallb-operator
spec:
  namespace: metallb-system
  serviceAccount:
    name: metallb-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: metallb-operator
      channels:
        - stable
