apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true  
spec:
  channel: stable-4.22
  desiredUpdate:
    version: 4.22.0-0.nightly-2026-04-13-230307
    image: "registry.ci.openshift.org/ocp/release@sha256:18f0a3628337b939328404158000cd75774696014aacf6040b9ad0874843a98b"
