apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Network 1522 via OVS Bridge
  name: vlan-1522
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vlan-1522",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "default/vlan-1522",
      "vlanID": 1522,
      "mtu": 1500
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Network 2901 via OVS Bridge
  name: vlan-2901
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vlan-2901",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "default/vlan-2901",
      "vlanID": 2901,
      "mtu": 1500
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Network 2901 via OVS Bridge
  name: vlan-2901-1
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vlan-2901",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "default/vlan-2901-1",
      "vlanID": 2901,
      "mtu": 1500
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Network 2901 via OVS Bridge
  name: vlan-2901-2
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vlan-2901",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "default/vlan-2901-2",
      "vlanID": 2901,
      "mtu": 1500
    }    
---
#VLAN2901: 192.168.90.0/24
#VLAN2911: 192.168.91.0/24
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Network 2911 via linux Bridge
  name: vlan-2911-iscsi
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vlan-2911-iscsi",
      "type": "bridge",
      "bridge": "linux-br-iscsi",
      "mtu": 1500,
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.91.0/24"
      }    
    }        