---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: openshift-cert-manager-operator
spec:
  namespace: cert-manager
  serviceAccount:
    name: cert-manager-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: openshift-cert-manager-operator
      channels:
        - stable-v1
