apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reflector-operator

resources:
  - ./namespace.yaml
  - ./rbac.yaml

helmGlobals:
  chartHome: ../../.helm-charts

helmCharts:
  - name: reflector
    namespace: reflector-operator
    releaseName: reflector-operator